### ISSUE TITLE
typo in topic: Static File Options, Disabling Static Files label:bug

### ISSUE THREAD

**Issue by arthurkulchenko** [kemalcr/kemalcr.com#18]
Since Kemal::Config#serve_static is proprty it produces an error:
 `wrong number of arguments for 'Kemal::Config#serve_static' (given 1, expected 0)`
"=" should be added.
[pr]( https://github.com/kemalcr/kemalcr.com/pull/19/files)

**Comment by sdogruyol** [comment]
@arthurkulchenko thanks for the issue. However you need to use the helper `serve_static false` instead of calling `Kemal.config.serve_static` directly.

**Comment by arthurkulchenko** [comment]
I confused, where it should be applied, and I thought that should be a directory with configs as well.
