### ISSUE TITLE
Document websocket context

### ISSUE THREAD

**Issue by plainas** [kemalcr/kemalcr.com#22]
As discussed in this issue:
https://github.com/kemalcr/kemal/issues/295#issuecomment-281655432

**Comment by sdogruyol** [comment]
Thanks for the issue @plainas , this definitely needs more docs :+1:

**Comment by sdogruyol** [comment]
Fixed via https://github.com/kemalcr/kemalcr.com/commit/03fd1aee8d60a6e2d60caa4ee0440206f21db48f
