### ISSUE TITLE
Change to a stub

### ISSUE THREAD

**Issue by bararchy** [kemalcr/kemalcr.com#36]
Can we change this example: https://github.com/kemalcr/kemalcr.com/blob/master/_cookbook/code/cors/app.cr#L5 to "MYDOMAIN" etc.. to avoid copy-paste of `"*"` as an insecure value?

**Comment by straight-shoota** [comment]
`example.com`?

**Comment by bararchy** [comment]
Sure :) makes sense

**Comment by sdogruyol** [comment]
Fixed by https://github.com/kemalcr/kemalcr.com/commit/51e997dd31e628e0d79ecb9c83fea4f82731f1e6#diff-9d52d4c3543d93e2a6fa1f25a1db50a6
