### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by yujiri8** [kemalcr/kemalcr.com#39]
I'm not sure if this is really kemalcr.com's or crystal-lang.org's fault, but the link at the top of https://kemalcr.com/guide/ to https://crystal-lang.org/reference/installation/ is 404'd.

**Comment by yujiri8** [comment]
Another one: at https://kemalcr.com/community/, the link "Mailing List" points to a Google groups URL that says "Content unavailable".

**Comment by sdogruyol** [comment]
These are fixed now, thanks 🙏
