### ISSUE TITLE
text not displayed correctly for "using common paths"

### ISSUE THREAD

**Issue by nichady** [kemalcr/kemalcr.com#58]
https://kemalcr.com/guide/#using-common-paths

![image](https://user-images.githubusercontent.com/57887348/164789562-f5ed8260-8095-400e-a7eb-6183286d23e2.png)

**Comment by zw963** [comment]
Yes, i saw this too.

the source is like this: see screenshot.

![image](https://user-images.githubusercontent.com/549126/174434810-e4ad9926-1e13-4bc9-a25c-74c400fc3ec7.png)

**Comment by sdogruyol** [comment]
This is now fixed

See
<img width="871" alt="Screenshot 2023-02-19 at 09 24 41" src="https://user-images.githubusercontent.com/990485/219932628-94ca7562-4e0c-4932-b0a0-7d69e50cf5d3.png">
